
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Sep 19 2025 20:52:04 IST (Sep 19 2025 15:22:04 UTC)

// Verification Directory fv/lock 

module lock(clock, reset, x, ready, unlock, error, SE, scan_in,
     scan_out);
  input clock, reset, x, SE, scan_in;
  output ready, unlock, error, scan_out;
  wire clock, reset, x, SE, scan_in;
  wire ready, unlock, error, scan_out;
  wire [2:0] state;
  wire n_3, n_9, n_14, n_20, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_29, n_30, n_31, n_32, n_34, n_35;
  wire n_36, n_37;
  sdcrq1 \state_reg[0] (.CDN (n_37), .CP (clock), .D (n_36), .SD
       (scan_in), .SC (SE), .Q (state[0]));
  sdcrq1 \state_reg[1] (.CDN (n_37), .CP (clock), .D (n_35), .SD
       (state[0]), .SC (SE), .Q (state[1]));
  sdcrq1 \state_reg[2] (.CDN (n_37), .CP (clock), .D (n_31), .SD
       (state[1]), .SC (SE), .Q (scan_out));
  oai211d1 g619(.A (n_34), .B (n_22), .C1 (n_32), .C2 (state[0]), .ZN
       (n_36));
  oai211d1 g621(.A (n_34), .B (n_9), .C1 (state[1]), .C2 (n_3), .ZN
       (n_35));
  oaim31d1 g624(.A (n_30), .B1 (x), .B2 (n_32), .B3 (state[0]), .ZN
       (error));
  oai221d1 g622(.A (n_32), .B1 (n_23), .B2 (scan_out), .C1 (n_27), .C2
       (n_29), .ZN (n_31));
  aoi21d1 g625(.A (n_26), .B1 (n_24), .B2 (n_29), .ZN (n_30));
  oaim31d1 g623(.A (n_25), .B1 (n_27), .B2 (n_29), .B3 (n_20), .ZN
       (ready));
  aoi21d1 g626(.A (n_26), .B1 (n_29), .B2 (state[1]), .ZN (n_34));
  nd03d1 g628(.A1 (n_24), .A2 (scan_out), .A3 (state[0]), .ZN (n_25));
  nr02d1 g629(.A1 (n_32), .A2 (x), .ZN (n_26));
  inv0d0 g633(.I (n_24), .ZN (n_23));
  aon211d1 g627(.A (x), .B (n_14), .C1 (state[1]), .C2 (state[0]), .ZN
       (n_22));
  nr03d1 g630(.A1 (state[0]), .A2 (n_20), .A3 (n_14), .ZN (unlock));
  nr02d0 g634(.A1 (n_20), .A2 (x), .ZN (n_24));
  nd02d1 g635(.A1 (n_20), .A2 (scan_out), .ZN (n_32));
  nd02d1 g631(.A1 (x), .A2 (state[1]), .ZN (n_9));
  nr02d1 g632(.A1 (state[0]), .A2 (scan_out), .ZN (n_29));
  inv0d0 g636(.I (scan_out), .ZN (n_14));
  inv0d0 g640(.I (state[1]), .ZN (n_20));
  inv0d0 g639(.I (state[0]), .ZN (n_3));
  inv0d0 g637(.I (x), .ZN (n_27));
  inv0d0 g638(.I (reset), .ZN (n_37));
endmodule

