
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Sep 19 2025 18:09:52 IST (Sep 19 2025 12:39:52 UTC)

// Verification Directory fv/lock 

module lock(clock, reset, x, ready, unlock, error);
  input clock, reset, x;
  output ready, unlock, error;
  wire clock, reset, x;
  wire ready, unlock, error;
  wire [2:0] state;
  wire n_0, n_1, n_2, n_4, n_5, n_6, n_7, n_8;
  wire n_10, n_11, n_12, n_13, n_15, n_16, n_17, n_18;
  wire n_19;
  aon211d1 g360(.A (n_16), .B (n_15), .C1 (n_2), .C2 (state[2]), .ZN
       (n_18));
  oai221d1 g362(.A (n_16), .B1 (state[1]), .B2 (n_1), .C1 (n_15), .C2
       (n_8), .ZN (n_17));
  oaim31d1 g365(.A (n_11), .B1 (x), .B2 (n_12), .B3 (state[0]), .ZN
       (error));
  oai221d1 g363(.A (n_12), .B1 (n_4), .B2 (state[2]), .C1 (n_15), .C2
       (n_10), .ZN (n_13));
  aoi21d1 g366(.A (n_7), .B1 (n_5), .B2 (n_10), .ZN (n_11));
  oaim31d1 g364(.A (n_6), .B1 (n_15), .B2 (n_10), .B3 (n_8), .ZN
       (ready));
  aoi21d1 g368(.A (n_7), .B1 (n_10), .B2 (state[1]), .ZN (n_16));
  nd03d1 g367(.A1 (n_5), .A2 (state[2]), .A3 (state[0]), .ZN (n_6));
  nr02d0 g369(.A1 (x), .A2 (n_12), .ZN (n_7));
  inv0d0 g373(.I (n_5), .ZN (n_4));
  nr03d1 g370(.A1 (state[0]), .A2 (n_8), .A3 (n_0), .ZN (unlock));
  aoi22d1 g371(.A1 (n_8), .A2 (n_1), .B1 (state[1]), .B2 (state[0]),
       .ZN (n_2));
  nd02d1 g374(.A1 (state[2]), .A2 (n_8), .ZN (n_12));
  nr02d1 g375(.A1 (n_8), .A2 (x), .ZN (n_5));
  nr02d1 g372(.A1 (state[0]), .A2 (state[2]), .ZN (n_10));
  inv0d0 g379(.I (x), .ZN (n_15));
  inv0d0 g378(.I (reset), .ZN (n_19));
  dfcrb1 \state_reg[0] (.CDN (n_19), .CP (clock), .D (n_18), .Q
       (state[0]), .QN (n_1));
  dfcrb1 \state_reg[2] (.CDN (n_19), .CP (clock), .D (n_13), .Q
       (state[2]), .QN (n_0));
  dfcrb1 \state_reg[1] (.CDN (n_19), .CP (clock), .D (n_17), .Q
       (state[1]), .QN (n_8));
endmodule

